### ISSUE TITLE
ApiTests non-deterministically fail on Ubuntu

### ISSUE THREAD

**Issue by dvoits** [itislab/alpheus#49] opened 2019-09-20 12:35 UTC
See failed tests in the following build:

https://travis-ci.org/itislab/alpheus/builds/587449940?utm_source=github_status&utm_medium=notification

**Comment by dvoits** [comment] 2019-09-20 17:06
See also 
https://travis-ci.org/itislab/alpheus/builds/587572517?utm_source=github_status&utm_medium=notification

**Comment by dgrechka** [comment] 2020-01-14 19:52
The failing tests are resolved by PR #53 . But the reason for the failures are not determined.
Thus, leaving this bug open.

**Comment by dgrechka** [comment] 2020-01-20 20:21
Test triggering the issue is disabled in a865b45

**Comment by dgrechka** [comment] 2020-01-21 18:38
Considering this one as fixed by the PR #64

**Closed as completed by dgrechka** 2020-01-21 18:38 UTC
Labels: bug
